In [2]:
# Import necessary libraries
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

# Load the dataset
df = pd.read_excel(r"C:\Users\Revathy\Desktop\data_4.xlsx")

# Check the basic details of the dataset
print(df.info())
print(df.describe())

# Fill in missing values
for col in df.columns:
    if df[col].dtype == 'object':
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna(df[col].mean(), inplace=True)

# Check and handle outliers in at least 3 columns in the dataset
columns_to_check = ['Pclass', 'Age', 'Fare']

for col in columns_to_check:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    df = df[(df[col] >= Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]

# Do min max scaling on the numeric columns
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
scaler = MinMaxScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# Check the dataset after transformations
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200
   PassengerId  Survived  Pclass  \
0     0.000000       0.0     1.0
2     0.002247       1.0     1.0
3     0.003371       1.0     0.0
4     0.004494       0.0     1.0
5     0.005618       0.0     1.0

                                           Name     Sex       Age  SibSp  \
0                       Braund, Mr. Owen Harris    male  0.372549    0.2
2                        Heikkinen, Miss. Laina  female  0.450980    0.0
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  0.627451    0.2
4                      Allen, Mr. William Henry    male  0.627451    0.0
5                              Moran, Mr. James    male  0.523512    0.0

   Parch            Ticket      Fare    Cabin Embarked
0    0.0         A/5 21171  0.118118  B96 B98        S
2    0.0  STON/O2. 3101282  0.129115  B96 B98        S
3    0.0            113803  0.865114     C123        S
4    0.0            373450  0.131152  B96 B98        S
5    0.0            330877  0.137804  B96 B98        Q

C:\Users\Revathy\AppData\Local\Temp\ipykernel_5004\427758165.py:16: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df[col].fillna(df[col].mode()[0], inplace=True)